# Generated by Django 3.1.7 on 2021-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='Original url')),
                ('short_url', models.URLField(verbose_name='Short url')),
            ],
        ),
    ]
